export type Queue = "open" | "waiting" | "deadline";

export type Desk = "charge" | "calls" | "tracker" | "cloud" | "records" | "appeals" | "billing";

export type DeskView = "work-hub" | "managers-view";

export type StepStatus = "complete" | "current" | "upcoming";

export type Step = {
  label: string;
  status: StepStatus;
};

export type HistoryEntry = {
  id: string;
  date: string;
  source: string;
  audience: string;
  text: string;
  minutes?: number;
};

export type ClaimField = {
  label: string;
  value: string;
};

export type Claim = {
  id: string;
  number: string;
  queue: Queue;
  desk: Desk;
  owner: string;
  patient: string;
  practice: string;
  statusLabel: string;
  urgency: string;
  flag: string;
  dueDate: string;
  payer: string;
  balance: string;
  note: string;
  nextStep: string;
  steps: Step[];
  history: HistoryEntry[];
  actions: string[];
  fields: ClaimField[];
  files: string[];
};

export type Person = {
  id: string;
  name: string;
  role: string;
  email: string;
  desk: Desk | "all";
};

export const PEOPLE: Person[] = [
  { id: "charge", name: "Charge review", role: "Charge review", email: "", desk: "charge" },
  { id: "calls", name: "Call center", role: "Call center", email: "", desk: "calls" },
  { id: "tracker", name: "Tracker leads", role: "Tracker leads", email: "", desk: "tracker" },
  { id: "cloud", name: "Cloud Staff", role: "Cloud Staff", email: "", desk: "cloud" },
  { id: "records", name: "Medical records", role: "Medical records", email: "", desk: "records" },
  { id: "appeals", name: "Appeals", role: "Appeals", email: "", desk: "appeals" },
  { id: "billing", name: "Billing", role: "Billing", email: "", desk: "billing" },
  { id: "all", name: "All claims", role: "All claims", email: "", desk: "all" },
];

export const DESK_VIEWS: { id: DeskView; href: string; label: string }[] = [
  { id: "work-hub", href: "/", label: "Work Hub" },
  { id: "managers-view", href: "/managers-view", label: "Manager's View" },
];

const QUEUE_DOT: Record<Queue, string> = {
  open: "/figma/status-open.svg",
  waiting: "/figma/status-waiting.svg",
  deadline: "/figma/status-deadline.svg",
};

export function queueDot(queue: Queue) {
  return QUEUE_DOT[queue];
}

export function stepsThrough(labels: string[], currentIndex: number): Step[] {
  return labels.map((label, index) => ({
    label,
    status:
      index < currentIndex
        ? "complete"
        : index === currentIndex
          ? "current"
          : "upcoming",
  }));
}

export function advanceSteps(steps: Step[]): Step[] {
  const currentIndex = steps.findIndex((step) => step.status === "current");
  if (currentIndex === -1) return steps;

  return steps.map((step, index) => {
    if (index < currentIndex) return step;
    if (index === currentIndex) return { ...step, status: "complete" };
    if (index === currentIndex + 1) return { ...step, status: "current" };
    return step;
  });
}

export const initialClaims: Claim[] = [
  {
    id: "ryan",
    number: "204739292",
    queue: "deadline",
    desk: "charge",
    owner: "Charge review",
    patient: "Ryan Cooper",
    practice: "Cedar Row ENT",
    statusLabel: "Charge review",
    urgency: "Urgent",
    flag: "White",
    dueDate: "Sep 28, 2026",
    payer: "Regence",
    balance: "$860.00",
    note: "Filing date is close. The nasal endoscopy is on file. The auth number is the piece that holds the claim.",
    nextStep: "Finish charge review, then Alicia can send it.",
    steps: stepsThrough(
      ["Clinic entered the visit", "Charge review", "Alicia sends the charge"],
      1,
    ),
    fields: [
      { label: "CPT", value: "31231" },
      { label: "Date of service", value: "Jul 9, 2026" },
      { label: "Subscriber ID", value: "On file" },
      { label: "Auth number", value: "Missing" },
      { label: "Credentialing", value: "Provider can bill Regence" },
    ],
    files: [],
    history: [
      {
        id: "ryan-1",
        date: "Sep 18, 2026",
        source: "Cedar Row ENT",
        audience: "Tracker",
        text: "New tracker row. Nasal endoscopy. CPT 31231.",
      },
      {
        id: "ryan-done",
        date: "Today",
        source: "Charge review",
        audience: "Charge review",
        text: "Step done.",
        minutes: 18,
      },
    ],
    actions: ["Ready for Alicia", "Waiting on clinic"],
  },
  {
    id: "noah",
    number: "174839205",
    queue: "open",
    desk: "calls",
    owner: "Call center",
    patient: "Noah Grant",
    practice: "Lakeside Allergy",
    statusLabel: "Call center",
    urgency: "Routine",
    flag: "White",
    dueDate: "Oct 15, 2026",
    payer: "Summit Blue",
    balance: "$2,460.00",
    note: "The clinic asked about a coordination-of-benefits balance. The call stays on this claim until Mallory has enough to move it.",
    nextStep: "Log the call. Move it when the coverage answer is complete.",
    steps: stepsThrough(
      ["Clinic asked about the balance", "Outbound call", "Move to tracker lead"],
      1,
    ),
    fields: [
      { label: "Who called", value: "Lakeside front desk" },
      { label: "About", value: "Coordination of benefits" },
      { label: "Call log", value: "Tue / Thu log, now on this claim" },
    ],
    files: [],
    history: [
      {
        id: "noah-1",
        date: "Sep 20, 2026",
        source: "Lakeside Allergy",
        audience: "Call center",
        text: "Email: patient says the other insurance should have paid.",
      },
    ],
    actions: ["Call again", "Enough to move"],
  },
  {
    id: "jonah",
    number: "583920471",
    queue: "open",
    desk: "cloud",
    owner: "Cloud Staff",
    patient: "Jonah Blake",
    practice: "Westbridge Orthopedics",
    statusLabel: "Not on file",
    urgency: "Urgent",
    flag: "White",
    dueDate: "Oct 2, 2026",
    payer: "Aetna",
    balance: "$4,280.00",
    note: "Worked first on the AR because the filing date is at risk. Portal check comes before a call.",
    nextStep: "Check the Aetna portal, then send the finding back.",
    steps: stepsThrough(
      ["Submitted in AdvancedMD", "White case", "Not on file follow-up"],
      2,
    ),
    fields: [
      { label: "AR tab", value: "Not on file" },
      { label: "Portal", value: "Not checked yet" },
      { label: "Member ID", value: "On file" },
      { label: "Diagnosis change", value: "Cloud Staff cannot make one" },
    ],
    files: [],
    history: [
      {
        id: "jonah-1",
        date: "Sep 18, 2026",
        source: "Jordan Hale",
        audience: "Cloud Staff",
        text: "White case. Please check whether Aetna has this claim.",
      },
    ],
    actions: ["Not on file — mail it", "On file — send back"],
  },
  {
    id: "ruth",
    number: "103847592",
    queue: "open",
    desk: "tracker",
    owner: "Tracker leads",
    patient: "Ruth Keller",
    practice: "Harbor & Pine Family Medicine",
    statusLabel: "Paid EOB",
    urgency: "Routine",
    flag: "White",
    dueDate: "Nov 2, 2026",
    payer: "Humana",
    balance: "$540.00",
    note: "Every code paid. Write the amounts, apply the office cap, then turn the row green.",
    nextStep: "Record the paid amount and patient responsibility.",
    steps: stepsThrough(
      ["EDI received", "Paid EOB on the tracker", "Turn the row green"],
      1,
    ),
    fields: [
      { label: "Paid amount", value: "$486.00" },
      { label: "Patient responsibility", value: "$54.00" },
      { label: "Office cap", value: "$40.00" },
      { label: "Auth notes", value: "Delete when the row turns green" },
    ],
    files: ["humana-eob.pdf"],
    history: [
      {
        id: "ruth-1",
        date: "Sep 22, 2026",
        source: "Crystal Hershon",
        audience: "Tracker",
        text: "EDI shows all codes paid. No denial.",
      },
    ],
    actions: ["Turn row green"],
  },
  {
    id: "adele",
    number: "920374851",
    queue: "waiting",
    desk: "records",
    owner: "Medical records",
    patient: "Adele Fraser",
    practice: "Harbor & Pine Family Medicine",
    statusLabel: "Waiting for medical records",
    urgency: "Urgent",
    flag: "Yellow",
    dueDate: "Oct 7, 2026",
    payer: "Medicare",
    balance: "$1,120.00",
    note: "The payer asked for the operative note. The claim stays here until that file is attached. The office saying they saw the request does not clear it.",
    nextStep: "Attach the operative note, then move the claim along.",
    steps: stepsThrough(
      ["Soft denial", "Waiting for medical records", "Send the record"],
      1,
    ),
    fields: [
      { label: "Request type", value: "Single patient" },
      { label: "Missing", value: "Operative note" },
      { label: "Date asked", value: "Sep 12, 2026" },
      { label: "Record", value: "Not attached" },
    ],
    files: [],
    history: [
      {
        id: "adele-1",
        date: "Sep 12, 2026",
        source: "Jordan Hale",
        audience: "Records",
        text: "Payer asked for the operative note. Tracker lead cannot pull it.",
      },
      {
        id: "adele-2",
        date: "Sep 20, 2026",
        source: "Harbor & Pine",
        audience: "Records",
        text: "Office marked the request seen. The record is still not here.",
      },
    ],
    actions: ["Attach record"],
  },
  {
    id: "elena",
    number: "438100221",
    queue: "deadline",
    desk: "appeals",
    owner: "Appeals",
    patient: "Elena Vasquez",
    practice: "Harbor ENT",
    statusLabel: "Reconsideration upheld",
    urgency: "Urgent",
    flag: "Red",
    dueDate: "Oct 7, 2026",
    payer: "BrightPath",
    balance: "$5,120.00",
    note: "A reconsideration was mailed and upheld. This is a hard denial, so appeals works it again.",
    nextStep: "Classify the denial before another letter goes out.",
    steps: stepsThrough(
      ["Tracker lead copied it to appeals", "Appeals", "Outcome"],
      1,
    ),
    fields: [
      { label: "Denial reason", value: "Medical necessity" },
      { label: "Tries used", value: "1 of 2" },
      { label: "Last send", value: "Mail" },
      { label: "Payer received it", value: "Yes. Upheld." },
    ],
    files: ["brightpath-denial.pdf"],
    history: [
      {
        id: "elena-1",
        date: "Sep 9, 2026",
        source: "Jordan Hale",
        audience: "Appeals",
        text: "Reconsideration was mailed and upheld. Copied to the appeals tab.",
      },
    ],
    actions: ["Dispute", "Adjust off"],
  },
  {
    id: "walter",
    number: "302948175",
    queue: "waiting",
    desk: "tracker",
    owner: "Tracker leads",
    patient: "Walter Briggs",
    practice: "Northline Pediatrics",
    statusLabel: "Do not call",
    urgency: "Routine",
    flag: "White",
    dueDate: "Sep 12, 2026",
    payer: "Aetna",
    balance: "$195.00",
    note: "Credentialing is open for this provider. Crystal confirmed it on the provider and payer list.",
    nextStep: "Leave it. Do not call Aetna until credentialing closes.",
    steps: stepsThrough(["Charge held", "Do not call", "Credentialing closes"], 1),
    fields: [
      { label: "Provider", value: "Dr. Avery Lang" },
      { label: "Payer", value: "Aetna" },
      { label: "Issue list", value: "Confirmed by Crystal" },
    ],
    files: [],
    history: [
      {
        id: "walter-1",
        date: "Sep 15, 2026",
        source: "Crystal Hershon",
        audience: "Tracker",
        text: "Yes. This is a credentialing issue. Do not call.",
      },
    ],
    actions: ["Keep on do not call"],
  },
  {
    id: "thomas",
    number: "438295710",
    queue: "waiting",
    desk: "cloud",
    owner: "Cloud Staff",
    patient: "Thomas Nguyen",
    practice: "Northline Pediatrics",
    statusLabel: "Called last time",
    urgency: "Routine",
    flag: "White",
    dueDate: "Oct 16, 2026",
    payer: "Providence",
    balance: "$240.00",
    note: "Portal said the claim was received. Check again around the 16th, including whether records arrived.",
    nextStep: "Follow up on the prior call.",
    steps: stepsThrough(["Not on file", "Called last time", "Still open"], 1),
    fields: [
      { label: "AR tab", value: "Called last time" },
      { label: "Last check", value: "Sep 16, 2026" },
      { label: "Portal", value: "Received" },
    ],
    files: [],
    history: [
      {
        id: "thomas-1",
        date: "Sep 16, 2026",
        source: "Priya Shah",
        audience: "Cloud Staff",
        text: "Providence portal says received. Check again in 30 days.",
      },
      {
        id: "thomas-done",
        date: "Today",
        source: "Cloud Staff",
        audience: "Cloud Staff",
        text: "Step done.",
        minutes: 22,
      },
    ],
    actions: ["Still open", "Paid but still on AR"],
  },
  {
    id: "zoe",
    number: "739204829",
    queue: "open",
    desk: "charge",
    owner: "Charge review",
    patient: "Zoe Bailey",
    practice: "Northline Pediatrics",
    statusLabel: "Unbilled",
    urgency: "Routine",
    flag: "White",
    dueDate: "Oct 20, 2026",
    payer: "Aetna",
    balance: "$195.00",
    note: "The charge never went out. Subscriber ID is outside the effective date. That is a simple correction.",
    nextStep: "Correct the subscriber ID, then return to the charge review tab.",
    steps: stepsThrough(["Unbilled", "Simple correction", "Alicia sends the charge"], 1),
    fields: [
      { label: "CPT", value: "99213" },
      { label: "Date of service", value: "Sep 2, 2026" },
      { label: "Subscriber ID", value: "Outside effective date" },
      { label: "Issue", value: "Simple" },
    ],
    files: [],
    history: [],
    actions: ["Ready for Alicia", "Waiting on clinic"],
  },
  {
    id: "ethan",
    number: "203749292",
    queue: "open",
    desk: "charge",
    owner: "Charge review",
    patient: "Ethan Russell",
    practice: "Cedar Row ENT",
    statusLabel: "Rejection",
    urgency: "Urgent",
    flag: "White",
    dueDate: "Oct 4, 2026",
    payer: "Regence",
    balance: "$640.00",
    note: "The clearinghouse rejected it. The rejection reason is not always the real reason.",
    nextStep: "Review the rejection in Claims Center, then scan for overnight add-ons.",
    steps: stepsThrough(["Submitted", "Clearinghouse rejection", "Charge review"], 1),
    fields: [
      { label: "CPT", value: "31231" },
      { label: "Where", value: "Claims Center · Exclusions" },
      { label: "Rejection", value: "Payer-specific rule" },
      { label: "Credentialing", value: "Clear" },
    ],
    files: [],
    history: [],
    actions: ["Ready for Alicia", "Waiting on clinic"],
  },
  {
    id: "brian",
    number: "203492972",
    queue: "open",
    desk: "calls",
    owner: "Call center",
    patient: "Brian Carter",
    practice: "Harbor ENT",
    statusLabel: "Inbound call",
    urgency: "Routine",
    flag: "White",
    dueDate: "Oct 18, 2026",
    payer: "BrightPath",
    balance: "$320.00",
    note: "The clinic emailed a question. It is logged on this claim. A simple answer can close the call.",
    nextStep: "Log what they asked. Move it if the answer is complete.",
    steps: stepsThrough(["Inbound email", "Log the call", "Move along"], 1),
    fields: [
      { label: "Who called", value: "Harbor ENT" },
      { label: "About", value: "Claim status" },
      { label: "Simple or not", value: "Simple. About a minute." },
    ],
    files: [],
    history: [],
    actions: ["Call again", "Enough to move"],
  },
  {
    id: "emily",
    number: "204792639",
    queue: "waiting",
    desk: "calls",
    owner: "Call center",
    patient: "Emily Parker",
    practice: "Lakeside Allergy",
    statusLabel: "Second attempt",
    urgency: "Routine",
    flag: "White",
    dueDate: "Oct 22, 2026",
    payer: "Summit Blue",
    balance: "$180.00",
    note: "First patient-balance call had no answer. The next try is this week. After that, the balance can move to the patient.",
    nextStep: "Call again. A statement is the step after a second miss.",
    steps: stepsThrough(["First call", "Second attempt", "Statement"], 1),
    fields: [
      { label: "About", value: "Patient balance" },
      { label: "Last try", value: "Sep 18, 2026" },
      { label: "Call log", value: "On this claim" },
    ],
    files: [],
    history: [],
    actions: ["Call again", "Enough to move"],
  },
  {
    id: "chloe",
    number: "294203792",
    queue: "open",
    desk: "tracker",
    owner: "Tracker leads",
    patient: "Chloe Griffin",
    practice: "Cedar Row ENT",
    statusLabel: "White case",
    urgency: "Routine",
    flag: "White",
    dueDate: "Oct 30, 2026",
    payer: "Medicare",
    balance: "$1,040.00",
    note: "No EOB yet. Check that the claim is on file so it does not become a timely-filing denial.",
    nextStep: "Confirm it is on file, and note what insurance will pay.",
    steps: stepsThrough(["Submitted", "White case", "On file or not"], 1),
    fields: [
      { label: "Tracker color", value: "White" },
      { label: "On file", value: "Not checked" },
      { label: "Auth notes", value: "Still on the row" },
    ],
    files: [],
    history: [],
    actions: ["Ask Cloud Staff"],
  },
  {
    id: "michael",
    number: "392720849",
    queue: "open",
    desk: "cloud",
    owner: "Cloud Staff",
    patient: "Michael Bennett",
    practice: "Vale Cardiology",
    statusLabel: "New AR",
    urgency: "Routine",
    flag: "White",
    dueDate: "Nov 1, 2026",
    payer: "Moda",
    balance: "$3,050.00",
    note: "New on the non-surgical AR. Not on file is worked first. This one has not been called.",
    nextStep: "Check the portal before calling.",
    steps: stepsThrough(["New AR", "Portal check", "Call or send back"], 0),
    fields: [
      { label: "AR tab", value: "New claims" },
      { label: "Order", value: "After not-on-file" },
      { label: "Portal", value: "Not checked" },
    ],
    files: [],
    history: [],
    actions: ["On file — send back", "Not on file — mail it"],
  },
  {
    id: "sophia",
    number: "902347129",
    queue: "open",
    desk: "cloud",
    owner: "Cloud Staff",
    patient: "Sophia Mitchell",
    practice: "Harbor & Pine Family Medicine",
    statusLabel: "Paid, still on AR",
    urgency: "Urgent",
    flag: "Green",
    dueDate: "Oct 9, 2026",
    payer: "Humana",
    balance: "$540.00",
    note: "Marked paid, full amount, but the row is still on the AR. That is a posting error, not another payer call.",
    nextStep: "Send it to billing. Do not call Humana.",
    steps: stepsThrough(["Called", "Paid CS follow-up", "Billing posts it"], 1),
    fields: [
      { label: "AR tab", value: "Paid, still on AR" },
      { label: "Marked", value: "Paid in full" },
      { label: "Balance", value: "Still open" },
    ],
    files: [],
    history: [],
    actions: ["Paid but still on AR"],
  },
  {
    id: "olivia",
    number: "349720292",
    queue: "waiting",
    desk: "records",
    owner: "Medical records",
    patient: "Olivia Hayes",
    practice: "Northline Pediatrics",
    statusLabel: "Waiting for medical records",
    urgency: "Routine",
    flag: "Yellow",
    dueDate: "Oct 21, 2026",
    payer: "Providence",
    balance: "$240.00",
    note: "On Records Needed. The office list goes out Friday. The claim stays yellow until the page is attached.",
    nextStep: "Wait for the clinic file, then attach it.",
    steps: stepsThrough(["Records requested", "Waiting for medical records", "Send the record"], 1),
    fields: [
      { label: "Request type", value: "Single patient" },
      { label: "Missing", value: "Office note" },
      { label: "Date asked", value: "Sep 19, 2026" },
      { label: "Record", value: "Not attached" },
    ],
    files: [],
    history: [],
    actions: ["Attach record"],
  },
  {
    id: "james",
    number: "729204392",
    queue: "open",
    desk: "records",
    owner: "Medical records",
    patient: "James Reynolds",
    practice: "Harbor ENT",
    statusLabel: "Record attached",
    urgency: "Routine",
    flag: "Yellow",
    dueDate: "Oct 11, 2026",
    payer: "Medicare",
    balance: "$890.00",
    note: "The operative note is on the claim. Codes, date of service, and the signature were checked. Send it by portal.",
    nextStep: "Send the record, then the claim can move.",
    steps: stepsThrough(["Waiting for medical records", "Record attached", "Send the record"], 1),
    fields: [
      { label: "Request type", value: "Single patient" },
      { label: "Record", value: "op-report.pdf" },
      { label: "How to send", value: "Portal, then fax" },
    ],
    files: ["op-report.pdf"],
    history: [],
    actions: ["Move along"],
  },
  {
    id: "isabella",
    number: "294372890",
    queue: "open",
    desk: "appeals",
    owner: "Appeals",
    patient: "Isabella Simmons",
    practice: "Cedar Row ENT",
    statusLabel: "Coding error",
    urgency: "Routine",
    flag: "Red",
    dueDate: "Oct 19, 2026",
    payer: "Aetna",
    balance: "$760.00",
    note: "The denial is a coding error, not a payer dispute. Correct it and rebuild. This is not a diagnosis change for Cloud Staff.",
    nextStep: "Correct the code, then resubmit.",
    steps: stepsThrough(["Red on the tracker", "Coding error", "Resubmit"], 1),
    fields: [
      { label: "Denial reason", value: "Coding" },
      { label: "CPT", value: "31231" },
      { label: "Tries used", value: "0 of 2" },
    ],
    files: ["aetna-denial.pdf"],
    history: [],
    actions: ["Correct and resubmit"],
  },
  {
    id: "mia",
    number: "920472839",
    queue: "waiting",
    desk: "appeals",
    owner: "Appeals",
    patient: "Mia Lawson",
    practice: "Westbridge Orthopedics",
    statusLabel: "Valid denial",
    urgency: "Routine",
    flag: "Red",
    dueDate: "Oct 28, 2026",
    payer: "Moda",
    balance: "$210.00",
    note: "Tries are used up. The denial stands. Adjust it off. There is no tracker color for that yet.",
    nextStep: "Adjust off, and record why.",
    steps: stepsThrough(["Appeal sent", "Upheld", "Adjust off"], 2),
    fields: [
      { label: "Denial reason", value: "Valid. Tries exhausted." },
      { label: "Tries used", value: "2 of 2" },
      { label: "Last send", value: "Fax" },
    ],
    files: [],
    history: [],
    actions: ["Adjust off"],
  },
  {
    id: "david",
    number: "729203494",
    queue: "open",
    desk: "billing",
    owner: "Billing",
    patient: "David Foster",
    practice: "Harbor & Pine Family Medicine",
    statusLabel: "Ready to post",
    urgency: "Routine",
    flag: "White",
    dueDate: "Oct 12, 2026",
    payer: "Humana",
    balance: "$540.00",
    note: "The ERA line is green and the remark is PR1. Insurance paid, and the rest is the patient deductible.",
    nextStep: "Post the payment. Do not treat green alone as done.",
    steps: stepsThrough(["EDI received", "ERA review", "Post payment"], 1),
    fields: [
      { label: "Insurance paid", value: "$486.00" },
      { label: "Patient paid", value: "$0.00" },
      { label: "Patient responsibility", value: "$54.00" },
      { label: "Write-off", value: "$0.00" },
      { label: "Remark", value: "PR1 deductible" },
      { label: "Date of service", value: "Aug 4, 2026" },
      { label: "CPT", value: "99214" },
    ],
    files: ["humana-eob.pdf"],
    history: [],
    actions: ["Post payment", "Hold — do not bill patient"],
  },
  {
    id: "andrew",
    number: "204739293",
    queue: "open",
    desk: "billing",
    owner: "Billing",
    patient: "Andrew Powell",
    practice: "Cedar Row ENT",
    statusLabel: "Hold",
    urgency: "Urgent",
    flag: "White",
    dueDate: "Oct 8, 2026",
    payer: "Regence",
    balance: "$860.00",
    note: "The line looks green, but there is no payment and no write-off. Posting it would bill the patient.",
    nextStep: "Hold it. The denial stays on the patient account.",
    steps: stepsThrough(["ERA line", "Hold", "Work from the EDI"], 1),
    fields: [
      { label: "Insurance paid", value: "$0.00" },
      { label: "Write-off", value: "None" },
      { label: "Remark", value: "Code did not pay" },
      { label: "ERA color", value: "Green. Not safe." },
      { label: "CPT", value: "31231" },
    ],
    files: ["regence-eob.pdf"],
    history: [],
    actions: ["Hold — do not bill patient"],
  },
  {
    id: "lily",
    number: "294203793",
    queue: "waiting",
    desk: "billing",
    owner: "Billing",
    patient: "Lily Reed",
    practice: "Lakeside Allergy",
    statusLabel: "Copay over-apply",
    urgency: "Routine",
    flag: "White",
    dueDate: "Oct 14, 2026",
    payer: "Summit Blue",
    balance: "$15.00",
    note: "The ERA would over-apply $15 because the patient already paid a copay.",
    nextStep: "Unapply the copay, then post.",
    steps: stepsThrough(["ERA line", "Copay conflict", "Post payment"], 1),
    fields: [
      { label: "Insurance paid", value: "$120.00" },
      { label: "Patient paid", value: "$15.00 copay" },
      { label: "Over-apply", value: "$15.00" },
      { label: "CPT", value: "95004" },
    ],
    files: [],
    history: [],
    actions: ["Unapply copay", "Hold — do not bill patient"],
  },
  {
    id: "daniel",
    number: "392720850",
    queue: "open",
    desk: "billing",
    owner: "Billing",
    patient: "Daniel Price",
    practice: "Northline Pediatrics",
    statusLabel: "Denial off the ERA",
    urgency: "Routine",
    flag: "Red",
    dueDate: "Oct 16, 2026",
    payer: "Aetna",
    balance: "$240.00",
    note: "Holding the line took it off the ERA. The denial is still on the patient account and has to be worked from the EDI.",
    nextStep: "Send the denial to the tracker lead. Do not treat the ERA as clear.",
    steps: stepsThrough(["ERA denial", "Held off the ERA", "Tracker lead works the EDI"], 1),
    fields: [
      { label: "Insurance paid", value: "$0.00" },
      { label: "Write-off", value: "None" },
      { label: "Where it sits", value: "Patient account, not the ERA" },
      { label: "CPT", value: "99213" },
    ],
    files: ["aetna-eob.pdf"],
    history: [],
    actions: ["Hold — do not bill patient"],
  },
];

function extra(
  claim: Pick<
    Claim,
    | "id"
    | "number"
    | "desk"
    | "owner"
    | "patient"
    | "practice"
    | "payer"
    | "balance"
    | "dueDate"
    | "statusLabel"
    | "flag"
    | "queue"
    | "note"
    | "nextStep"
    | "steps"
    | "fields"
    | "actions"
  > &
    Partial<Claim>,
): Claim {
  return {
    urgency: "Routine",
    files: [],
    history: [],
    ...claim,
  };
}

const extraClaims: Claim[] = [
  extra({
    id: "harper",
    number: "610284731",
    desk: "charge",
    owner: "Charge review",
    queue: "open",
    patient: "Harper Quinn",
    practice: "Cedar Row ENT",
    payer: "Regence",
    balance: "$430.00",
    dueDate: "Oct 18, 2026",
    statusLabel: "Overnight add-on",
    flag: "White",
    note: "A charge was added overnight. The morning scan still has to catch it.",
    nextStep: "Scan yesterday’s visits for add-ons, then send it on.",
    steps: stepsThrough(["Unbilled", "Overnight add-on", "Alicia sends the charge"], 1),
    fields: [
      { label: "CPT", value: "31237" },
      { label: "Date of service", value: "Sep 23, 2026" },
      { label: "Issue", value: "Simple" },
    ],
    actions: ["Ready for Alicia", "Waiting on clinic"],
  }),
  extra({
    id: "nina",
    number: "610284732",
    desk: "charge",
    owner: "Charge review",
    queue: "waiting",
    patient: "Nina Patel",
    practice: "Harbor ENT",
    payer: "Aetna",
    balance: "$275.00",
    dueDate: "Oct 9, 2026",
    statusLabel: "Credentialing hold",
    flag: "White",
    note: "The provider is not approved to bill Aetna. The charge stays here until credentialing closes.",
    nextStep: "Do not send this to Alicia.",
    steps: stepsThrough(["Charge review", "Credentialing hold", "Alicia sends the charge"], 1),
    fields: [
      { label: "Provider", value: "Dr. Avery Lang" },
      { label: "Credentialing", value: "Not approved" },
      { label: "CPT", value: "99213" },
    ],
    actions: ["Waiting on clinic"],
  }),
  extra({
    id: "omar",
    number: "610284733",
    desk: "charge",
    owner: "Charge review",
    queue: "deadline",
    patient: "Omar Singh",
    practice: "Northline Pediatrics",
    payer: "Medicare",
    balance: "$510.00",
    dueDate: "Sep 30, 2026",
    statusLabel: "Charge review",
    urgency: "Urgent",
    flag: "White",
    note: "Filing date is close. Codes and the subscriber ID look fine.",
    nextStep: "Finish the review so Alicia can send it.",
    steps: stepsThrough(["Clinic entered the visit", "Charge review", "Alicia sends the charge"], 1),
    fields: [
      { label: "CPT", value: "99214" },
      { label: "Subscriber ID", value: "On file" },
      { label: "Auth number", value: "Not required" },
    ],
    actions: ["Ready for Alicia"],
  }),
  extra({
    id: "paige",
    number: "610284741",
    desk: "calls",
    owner: "Call center",
    queue: "open",
    patient: "Paige Nguyen",
    practice: "Lakeside Allergy",
    payer: "Summit Blue",
    balance: "$90.00",
    dueDate: "Oct 20, 2026",
    statusLabel: "Inbound call",
    flag: "White",
    note: "The clinic asked why a line was denied. Log the answer on this claim.",
    nextStep: "Log the call. Move it when the answer is complete.",
    steps: stepsThrough(["Inbound email", "Log the call", "Move along"], 1),
    fields: [
      { label: "Who called", value: "Lakeside billing" },
      { label: "About", value: "Denial question" },
    ],
    actions: ["Call again", "Enough to move"],
  }),
  extra({
    id: "quinn",
    number: "610284742",
    desk: "calls",
    owner: "Call center",
    queue: "waiting",
    patient: "Quinn Alvarez",
    practice: "Harbor & Pine Family Medicine",
    payer: "Humana",
    balance: "$220.00",
    dueDate: "Oct 25, 2026",
    statusLabel: "Coordination of benefits",
    flag: "White",
    note: "This may not be a true coordination-of-benefits denial. The call center is checking.",
    nextStep: "Confirm which insurance is primary, then move it.",
    steps: stepsThrough(["COB question", "Outbound call", "Move along"], 1),
    fields: [
      { label: "About", value: "Coordination of benefits" },
      { label: "Last try", value: "Sep 21, 2026" },
    ],
    history: [
      {
        id: "quinn-1",
        date: "Sep 21, 2026",
        source: "Call center",
        audience: "Call center",
        text: "Clinic says the spouse’s plan should be primary.",
      },
    ],
    actions: ["Call again", "Enough to move"],
  }),
  extra({
    id: "rosa",
    number: "610284743",
    desk: "calls",
    owner: "Call center",
    queue: "open",
    patient: "Rosa Bennett",
    practice: "Cedar Row ENT",
    payer: "Regence",
    balance: "$65.00",
    dueDate: "Oct 11, 2026",
    statusLabel: "Patient balance",
    flag: "White",
    note: "The patient is contesting the remaining balance. The payment itself happens outside the hub.",
    nextStep: "Log the contest, then decide if a statement goes out.",
    steps: stepsThrough(["Patient called", "Second attempt", "Statement"], 0),
    fields: [
      { label: "About", value: "Patient balance" },
      { label: "Who called", value: "Patient" },
    ],
    actions: ["Call again", "Enough to move"],
  }),
  extra({
    id: "samir",
    number: "610284751",
    desk: "tracker",
    owner: "Tracker leads",
    queue: "open",
    patient: "Samir Shah",
    practice: "Westbridge Orthopedics",
    payer: "Moda",
    balance: "$1,480.00",
    dueDate: "Oct 19, 2026",
    statusLabel: "Paid EOB",
    flag: "White",
    note: "All codes paid. Write the amounts and turn the row green.",
    nextStep: "Record the paid amount and patient responsibility.",
    steps: stepsThrough(["EDI received", "Paid EOB on the tracker", "Turn the row green"], 1),
    fields: [
      { label: "Paid amount", value: "$1,260.00" },
      { label: "Patient responsibility", value: "$220.00" },
      { label: "Office cap", value: "None" },
      { label: "Auth notes", value: "Delete when the row turns green" },
    ],
    files: ["moda-eob.pdf"],
    actions: ["Turn row green"],
  }),
  extra({
    id: "tara",
    number: "610284752",
    desk: "tracker",
    owner: "Tracker leads",
    queue: "waiting",
    patient: "Tara Brooks",
    practice: "Harbor ENT",
    payer: "Medicare",
    balance: "$640.00",
    dueDate: "Oct 6, 2026",
    statusLabel: "Soft denial",
    flag: "Yellow",
    urgency: "Urgent",
    note: "Medicare asked for the operative report. Tracker leads can pull this one.",
    nextStep: "Pull the op report, or send it to medical records if it is more than that.",
    steps: stepsThrough(["Red then yellow", "Soft denial", "Record sent"], 1),
    fields: [
      { label: "Tracker color", value: "Yellow" },
      { label: "Missing", value: "Operative note" },
    ],
    actions: ["Send to medical records"],
  }),
  extra({
    id: "uma",
    number: "610284753",
    desk: "tracker",
    owner: "Tracker leads",
    queue: "open",
    patient: "Uma Flores",
    practice: "Vale Cardiology",
    payer: "Aetna",
    balance: "$2,100.00",
    dueDate: "Sep 29, 2026",
    statusLabel: "Hard denial",
    flag: "Red",
    urgency: "Urgent",
    note: "The reconsideration was upheld. This is more than a tracker lead can send.",
    nextStep: "Copy it to appeals.",
    steps: stepsThrough(["Denial on the EDI", "Hard denial", "Appeals"], 1),
    fields: [
      { label: "Tracker color", value: "Red" },
      { label: "Denial reason", value: "Medical necessity" },
    ],
    actions: ["Send to appeals"],
  }),
  extra({
    id: "victor",
    number: "610284761",
    desk: "cloud",
    owner: "Cloud Staff",
    queue: "deadline",
    patient: "Victor Hale",
    practice: "Northline Pediatrics",
    payer: "Providence",
    balance: "$380.00",
    dueDate: "Sep 27, 2026",
    statusLabel: "Not on file",
    urgency: "Urgent",
    flag: "White",
    note: "Worked first. The filing date is inside the window.",
    nextStep: "Check the portal, then mail it if it is still not on file.",
    steps: stepsThrough(["New AR", "Not on file follow-up", "Mailed or on file"], 1),
    fields: [
      { label: "AR tab", value: "Not on file" },
      { label: "Portal", value: "Not on file" },
      { label: "Member ID", value: "On file" },
    ],
    actions: ["Not on file — mail it", "On file — send back"],
  }),
  extra({
    id: "wendy",
    number: "610284762",
    desk: "cloud",
    owner: "Cloud Staff",
    queue: "open",
    patient: "Wendy Cho",
    practice: "Harbor & Pine Family Medicine",
    payer: "Humana",
    balance: "$155.00",
    dueDate: "Oct 27, 2026",
    statusLabel: "Called last time",
    flag: "White",
    note: "Records were sent about 30 days ago. Confirm the payer received them.",
    nextStep: "Follow up on the prior call.",
    steps: stepsThrough(["Not on file", "Called last time", "Still open"], 1),
    fields: [
      { label: "AR tab", value: "Called last time" },
      { label: "Last check", value: "Aug 28, 2026" },
    ],
    actions: ["Still open", "On file — send back"],
  }),
  extra({
    id: "xavier",
    number: "610284763",
    desk: "cloud",
    owner: "Cloud Staff",
    queue: "open",
    patient: "Xavier Ortiz",
    practice: "Cedar Row ENT",
    payer: "Regence",
    balance: "$990.00",
    dueDate: "Nov 4, 2026",
    statusLabel: "New AR",
    flag: "White",
    note: "Not called yet. Portal check comes before the phone call.",
    nextStep: "Check the Regence portal.",
    steps: stepsThrough(["New AR", "Portal check", "Call or send back"], 0),
    fields: [
      { label: "AR tab", value: "New claims" },
      { label: "Portal", value: "Not checked" },
    ],
    actions: ["On file — send back", "Not on file — mail it"],
  }),
  extra({
    id: "yara",
    number: "610284771",
    desk: "records",
    owner: "Medical records",
    queue: "waiting",
    patient: "Yara Kim",
    practice: "Lakeside Allergy",
    payer: "Summit Blue",
    balance: "$410.00",
    dueDate: "Oct 13, 2026",
    statusLabel: "Waiting for medical records",
    flag: "Yellow",
    note: "The office was asked Friday. Seen is not the record.",
    nextStep: "Wait for the clinic file, then attach it.",
    steps: stepsThrough(["Records requested", "Waiting for medical records", "Send the record"], 1),
    fields: [
      { label: "Request type", value: "Single patient" },
      { label: "Missing", value: "Office note" },
      { label: "Date asked", value: "Sep 19, 2026" },
      { label: "Record", value: "Not attached" },
    ],
    actions: ["Attach record"],
  }),
  extra({
    id: "zane",
    number: "610284772",
    desk: "records",
    owner: "Medical records",
    queue: "open",
    patient: "Zane Cooper",
    practice: "Westbridge Orthopedics",
    payer: "Aetna",
    balance: "$1,750.00",
    dueDate: "Oct 17, 2026",
    statusLabel: "Record attached",
    flag: "Yellow",
    note: "The testing note is on the claim. Send it by fax. Portal is not available for this payer.",
    nextStep: "Send the record, then the claim can move.",
    steps: stepsThrough(["Waiting for medical records", "Record attached", "Send the record"], 1),
    fields: [
      { label: "Request type", value: "Single patient" },
      { label: "Record", value: "testing-note.pdf" },
      { label: "How to send", value: "Vonage fax" },
    ],
    files: ["testing-note.pdf"],
    actions: ["Send by portal"],
  }),
  extra({
    id: "ada",
    number: "610284773",
    desk: "records",
    owner: "Medical records",
    queue: "deadline",
    patient: "Ada Morales",
    practice: "Harbor ENT",
    payer: "Medicare",
    balance: "$2,400.00",
    dueDate: "Oct 1, 2026",
    statusLabel: "Waiting for medical records",
    urgency: "Urgent",
    flag: "Yellow",
    note: "One patient from a larger request. The page for this date of service is still missing.",
    nextStep: "Attach the missing page before the deadline.",
    steps: stepsThrough(["Bulk request", "Waiting for medical records", "Send the record"], 1),
    fields: [
      { label: "Request type", value: "Bulk mail" },
      { label: "Missing", value: "Operative note" },
      { label: "Date asked", value: "Sep 8, 2026" },
      { label: "Record", value: "Not attached" },
    ],
    actions: ["Attach record"],
  }),
  extra({
    id: "ben",
    number: "610284781",
    desk: "appeals",
    owner: "Appeals",
    queue: "open",
    patient: "Ben Carter",
    practice: "Cedar Row ENT",
    payer: "BrightPath",
    balance: "$3,300.00",
    dueDate: "Oct 5, 2026",
    statusLabel: "Reconsideration upheld",
    urgency: "Urgent",
    flag: "Red",
    note: "The first reconsideration was mailed and upheld. One try is left.",
    nextStep: "Dispute it before the response date.",
    steps: stepsThrough(["Copied to appeals", "Appeals", "Outcome"], 1),
    fields: [
      { label: "Denial reason", value: "Medical necessity" },
      { label: "Tries used", value: "1 of 2" },
      { label: "Last send", value: "Mail" },
    ],
    actions: ["Dispute"],
  }),
  extra({
    id: "cleo",
    number: "610284782",
    desk: "appeals",
    owner: "Appeals",
    queue: "open",
    patient: "Cleo Park",
    practice: "Northline Pediatrics",
    payer: "Aetna",
    balance: "$480.00",
    dueDate: "Oct 22, 2026",
    statusLabel: "Coding error",
    flag: "Red",
    note: "The modifier was rejected. Correct it and resubmit. This is not a diagnosis change.",
    nextStep: "Correct the modifier, then resubmit.",
    steps: stepsThrough(["Red on the tracker", "Coding error", "Resubmit"], 1),
    fields: [
      { label: "Denial reason", value: "Modifier" },
      { label: "CPT", value: "99213" },
      { label: "Tries used", value: "0 of 2" },
    ],
    actions: ["Correct and resubmit"],
  }),
  extra({
    id: "drew",
    number: "610284783",
    desk: "appeals",
    owner: "Appeals",
    queue: "waiting",
    patient: "Drew Ellis",
    practice: "Vale Cardiology",
    payer: "Moda",
    balance: "$860.00",
    dueDate: "Sep 18, 2026",
    statusLabel: "Valid denial",
    flag: "Red",
    note: "Both tries were used. The response date has passed. Adjust it off.",
    nextStep: "Adjust off, and record why.",
    steps: stepsThrough(["Appeal sent", "Upheld", "Adjust off"], 2),
    fields: [
      { label: "Denial reason", value: "Valid. Tries exhausted." },
      { label: "Tries used", value: "2 of 2" },
      { label: "Last send", value: "Portal" },
    ],
    actions: ["Adjust off"],
  }),
  extra({
    id: "elena-b",
    number: "610284791",
    desk: "billing",
    owner: "Billing",
    queue: "open",
    patient: "Elena Cho",
    practice: "Harbor & Pine Family Medicine",
    payer: "Humana",
    balance: "$730.00",
    dueDate: "Oct 15, 2026",
    statusLabel: "Ready to post",
    flag: "White",
    note: "Insurance paid. The remark is a contractual write-off, not a patient balance.",
    nextStep: "Post the payment in AdvancedMD.",
    steps: stepsThrough(["EDI received", "ERA review", "Post payment"], 1),
    fields: [
      { label: "Insurance paid", value: "$610.00" },
      { label: "Patient paid", value: "$0.00" },
      { label: "Patient responsibility", value: "$0.00" },
      { label: "Write-off", value: "$120.00" },
      { label: "Remark", value: "CO-45 contractual" },
      { label: "Date of service", value: "Aug 19, 2026" },
      { label: "CPT", value: "99214" },
    ],
    files: ["humana-cho-eob.pdf"],
    actions: ["Post payment"],
  }),
  extra({
    id: "finn",
    number: "610284792",
    desk: "billing",
    owner: "Billing",
    queue: "waiting",
    patient: "Finn Adler",
    practice: "Westbridge Orthopedics",
    payer: "Medicare",
    balance: "$1,100.00",
    dueDate: "Oct 3, 2026",
    statusLabel: "Hold",
    urgency: "Urgent",
    flag: "White",
    note: "Green on the ERA, no payment, no write-off. Do not post.",
    nextStep: "Hold it. The denial stays on the patient account.",
    steps: stepsThrough(["ERA line", "Hold", "Work from the EDI"], 1),
    fields: [
      { label: "Insurance paid", value: "$0.00" },
      { label: "Patient paid", value: "$0.00" },
      { label: "Patient responsibility", value: "$1,100.00" },
      { label: "Write-off", value: "None" },
      { label: "Remark", value: "Code did not pay" },
      { label: "Date of service", value: "Jul 30, 2026" },
      { label: "CPT", value: "27447" },
    ],
    actions: ["Hold — do not bill patient"],
  }),
  extra({
    id: "gina",
    number: "610284793",
    desk: "billing",
    owner: "Billing",
    queue: "open",
    patient: "Gina Walsh",
    practice: "Lakeside Allergy",
    payer: "Summit Blue",
    balance: "$45.00",
    dueDate: "Oct 29, 2026",
    statusLabel: "Copay over-apply",
    flag: "White",
    note: "The patient already paid a $25 copay. The ERA would apply it again.",
    nextStep: "Unapply the copay, then post.",
    steps: stepsThrough(["ERA line", "Copay conflict", "Post payment"], 1),
    fields: [
      { label: "Insurance paid", value: "$80.00" },
      { label: "Patient paid", value: "$25.00 copay" },
      { label: "Patient responsibility", value: "$25.00" },
      { label: "Write-off", value: "$0.00" },
      { label: "Over-apply", value: "$25.00" },
      { label: "Date of service", value: "Sep 4, 2026" },
      { label: "CPT", value: "95004" },
    ],
    actions: ["Unapply copay", "Hold — do not bill patient"],
  }),
];

initialClaims.push(...extraClaims);

const roster = [
  ["Harper", "Quinn"],
  ["Miles", "Okada"],
  ["Nora", "Feld"],
  ["Ivan", "Cruz"],
  ["Leah", "Stone"],
  ["Owen", "Blake"],
  ["Vera", "Nguyen"],
  ["Seth", "Park"],
  ["Maya", "Ross"],
  ["Joel", "Kim"],
  ["Iris", "Cole"],
  ["Theo", "Ward"],
  ["Lana", "Diaz"],
  ["Reid", "Shaw"],
  ["Cora", "Voss"],
  ["Dean", "Holt"],
  ["Nia", "Berg"],
  ["Paul", "Chen"],
  ["Ruth", "Abe"],
  ["Karl", "Nash"],
] as const;

const clinics = [
  "Cedar Row ENT",
  "Harbor ENT",
  "Lakeside Allergy",
  "Harbor & Pine Family Medicine",
  "Northline Pediatrics",
  "Westbridge Orthopedics",
  "Vale Cardiology",
];

const payers = ["Regence", "Aetna", "Medicare", "Summit Blue", "Humana", "Moda", "Providence", "BrightPath"];

let serial = 630100001;
let nameCursor = 0;

function more(
  desk: Claim["desk"],
  owner: string,
  statusLabel: string,
  queue: Claim["queue"],
  flag: string,
  note: string,
  nextStep: string,
  steps: Step[],
  fields: ClaimField[],
  actions: string[],
  urgency: Claim["urgency"] = "Routine",
  dueDate = "Oct 24, 2026",
): Claim {
  const [first, last] = roster[nameCursor % roster.length];
  nameCursor += 1;
  const number = String(serial);
  serial += 1;
  return extra({
    id: `m-${number}`,
    number,
    desk,
    owner,
    queue,
    patient: `${first} ${last}`,
    practice: clinics[serial % clinics.length],
    payer: payers[serial % payers.length],
    balance: `$${(180 + (serial % 17) * 85).toLocaleString("en-US")}.00`,
    dueDate,
    statusLabel,
    flag,
    urgency,
    note,
    nextStep,
    steps,
    fields,
    actions,
  });
}

const moreClaims: Claim[] = [
  ...Array.from({ length: 5 }, (_, index) =>
    more(
      "charge",
      "Charge review",
      "Charge review",
      index === 0 ? "deadline" : "open",
      "White",
      "Codes and the subscriber ID are in review.",
      "Finish charge review so Alicia can send it.",
      stepsThrough(["Clinic entered the visit", "Charge review", "Alicia sends the charge"], 1),
      [
        { label: "CPT", value: index % 2 ? "99214" : "31231" },
        { label: "Subscriber ID", value: "On file" },
        { label: "Auth number", value: "Not required" },
      ],
      ["Ready for Alicia"],
      index === 0 ? "Urgent" : "Routine",
      index === 0 ? "Oct 2, 2026" : "Nov 6, 2026",
    ),
  ),
  ...Array.from({ length: 4 }, () =>
    more(
      "charge",
      "Charge review",
      "Unbilled",
      "open",
      "White",
      "The charge never went out.",
      "Correct the simple error, then return to charge review.",
      stepsThrough(["Unbilled", "Simple correction", "Alicia sends the charge"], 1),
      [
        { label: "CPT", value: "99213" },
        { label: "Issue", value: "Simple" },
        { label: "Subscriber ID", value: "On file" },
      ],
      ["Ready for Alicia", "Waiting on clinic"],
    ),
  ),
  ...Array.from({ length: 3 }, () =>
    more(
      "charge",
      "Charge review",
      "Rejection",
      "open",
      "White",
      "The clearinghouse rejected it. The stated reason may not be the real one.",
      "Review the rejection, then scan for add-ons.",
      stepsThrough(["Submitted", "Clearinghouse rejection", "Charge review"], 1),
      [
        { label: "Where", value: "Claims Center · Exclusions" },
        { label: "Rejection", value: "Payer-specific rule" },
      ],
      ["Ready for Alicia", "Waiting on clinic"],
    ),
  ),
  ...Array.from({ length: 2 }, () =>
    more(
      "charge",
      "Charge review",
      "Credentialing hold",
      "waiting",
      "White",
      "This provider cannot bill this payer yet.",
      "Do not send this to Alicia.",
      stepsThrough(["Charge review", "Credentialing hold", "Alicia sends the charge"], 1),
      [
        { label: "Credentialing", value: "Not approved" },
        { label: "Provider", value: "Dr. Avery Lang" },
      ],
      ["Waiting on clinic"],
      "Routine",
      "Oct 8, 2026",
    ),
  ),
  ...Array.from({ length: 6 }, (_, index) =>
    more(
      "calls",
      "Call center",
      "Inbound call",
      "open",
      "White",
      "A clinic question is waiting to be logged on this claim.",
      "Log the call. Move it when the answer is complete.",
      stepsThrough(["Inbound email", "Log the call", "Move along"], 1),
      [
        { label: "Who called", value: "Clinic" },
        { label: "About", value: index % 2 ? "Claim status" : "Denial question" },
      ],
      ["Call again", "Enough to move"],
    ),
  ),
  ...Array.from({ length: 4 }, () =>
    more(
      "calls",
      "Call center",
      "Coordination of benefits",
      "waiting",
      "White",
      "Check whether this is a real coordination-of-benefits case.",
      "Confirm which insurance is primary.",
      stepsThrough(["COB question", "Outbound call", "Move along"], 1),
      [
        { label: "About", value: "Coordination of benefits" },
        { label: "Last try", value: "Sep 19, 2026" },
      ],
      ["Call again", "Enough to move"],
      "Routine",
      "Oct 16, 2026",
    ),
  ),
  ...Array.from({ length: 3 }, () =>
    more(
      "calls",
      "Call center",
      "Patient balance",
      "open",
      "White",
      "The patient is asking about the remaining balance.",
      "Log the call. A statement stays with the call center.",
      stepsThrough(["Patient called", "Second attempt", "Statement"], 1),
      [
        { label: "About", value: "Patient balance" },
        { label: "Who called", value: "Patient" },
      ],
      ["Call again", "Enough to move"],
    ),
  ),
  ...Array.from({ length: 1 }, () =>
    more(
      "calls",
      "Call center",
      "Second attempt",
      "waiting",
      "White",
      "The first call was not answered.",
      "Call again this week.",
      stepsThrough(["First call", "Second attempt", "Statement"], 1),
      [
        { label: "About", value: "Patient balance" },
        { label: "Last try", value: "Sep 15, 2026" },
      ],
      ["Call again", "Enough to move"],
    ),
  ),
  ...Array.from({ length: 5 }, () =>
    more(
      "tracker",
      "Tracker leads",
      "White case",
      "open",
      "White",
      "No EOB yet. Check that the claim is on file.",
      "Confirm it is on file, or ask Cloud Staff.",
      stepsThrough(["Submitted", "White case", "On file or not"], 1),
      [
        { label: "Tracker color", value: "White" },
        { label: "On file", value: "Not checked" },
      ],
      ["Ask Cloud Staff"],
      "Routine",
      "Nov 12, 2026",
    ),
  ),
  ...Array.from({ length: 4 }, () =>
    more(
      "tracker",
      "Tracker leads",
      "Paid EOB",
      "open",
      "White",
      "All codes paid. Write the amounts and turn the row green.",
      "Record the paid amount and patient responsibility.",
      stepsThrough(["EDI received", "Paid EOB on the tracker", "Turn the row green"], 1),
      [
        { label: "Paid amount", value: "$640.00" },
        { label: "Patient responsibility", value: "$40.00" },
        { label: "Office cap", value: "None" },
        { label: "Auth notes", value: "Delete when the row turns green" },
      ],
      ["Turn row green"],
    ),
  ),
  ...Array.from({ length: 3 }, (_, index) =>
    more(
      "tracker",
      "Tracker leads",
      "Soft denial",
      "waiting",
      "Yellow",
      "The payer asked for a simple operative report.",
      "Pull it here, or send it to medical records.",
      stepsThrough(["Denial on the EDI", "Soft denial", "Record sent"], 1),
      [
        { label: "Tracker color", value: "Yellow" },
        { label: "Missing", value: "Operative note" },
      ],
      ["Send to medical records"],
      index === 0 ? "Urgent" : "Routine",
      "Oct 7, 2026",
    ),
  ),
  ...Array.from({ length: 2 }, () =>
    more(
      "tracker",
      "Tracker leads",
      "Hard denial",
      "open",
      "Red",
      "This denial needs appeals.",
      "Copy it to appeals.",
      stepsThrough(["Denial on the EDI", "Hard denial", "Appeals"], 1),
      [
        { label: "Tracker color", value: "Red" },
        { label: "Denial reason", value: "Medical necessity" },
      ],
      ["Send to appeals"],
      "Urgent",
      "Oct 4, 2026",
    ),
  ),
  ...Array.from({ length: 6 }, (_, index) =>
    more(
      "cloud",
      "Cloud Staff",
      "Not on file",
      index < 2 ? "deadline" : "open",
      "White",
      "Not on file is worked before the other AR tabs.",
      "Check the portal, then mail it if it is still missing.",
      stepsThrough(["New AR", "Not on file follow-up", "Mailed or on file"], 1),
      [
        { label: "AR tab", value: "Not on file" },
        { label: "Portal", value: "Not on file" },
        { label: "Member ID", value: "On file" },
      ],
      ["Not on file — mail it", "On file — send back"],
      index < 2 ? "Urgent" : "Routine",
      index < 2 ? "Sep 26, 2026" : "Oct 21, 2026",
    ),
  ),
  ...Array.from({ length: 4 }, () =>
    more(
      "cloud",
      "Cloud Staff",
      "New AR",
      "open",
      "White",
      "Not called yet.",
      "Check the portal before calling.",
      stepsThrough(["New AR", "Portal check", "Call or send back"], 0),
      [
        { label: "AR tab", value: "New claims" },
        { label: "Portal", value: "Not checked" },
      ],
      ["On file — send back", "Not on file — mail it"],
      "Routine",
      "Nov 8, 2026",
    ),
  ),
  ...Array.from({ length: 2 }, () =>
    more(
      "cloud",
      "Cloud Staff",
      "Called last time",
      "waiting",
      "White",
      "Called before. Due for another check.",
      "Confirm the payer received the last packet.",
      stepsThrough(["Not on file", "Called last time", "Still open"], 1),
      [
        { label: "AR tab", value: "Called last time" },
        { label: "Last check", value: "Aug 20, 2026" },
      ],
      ["Still open", "On file — send back"],
    ),
  ),
  ...Array.from({ length: 1 }, () =>
    more(
      "cloud",
      "Cloud Staff",
      "Paid, still on AR",
      "open",
      "Green",
      "Marked paid, but the row is still on the AR. That is a posting error.",
      "Send it to billing. Do not call the payer.",
      stepsThrough(["Called", "Paid CS follow-up", "Billing posts it"], 1),
      [
        { label: "AR tab", value: "Paid, still on AR" },
        { label: "Marked", value: "Paid in full" },
        { label: "Insurance paid", value: "$0.00" },
        { label: "Write-off", value: "None" },
      ],
      ["Paid but still on AR"],
    ),
  ),
  ...Array.from({ length: 8 }, (_, index) =>
    more(
      "records",
      "Medical records",
      "Waiting for medical records",
      index < 2 ? "deadline" : "waiting",
      "Yellow",
      "The record is not attached. The office saying they saw the request does not clear it.",
      "Attach the missing page, then send it.",
      stepsThrough(["Records requested", "Waiting for medical records", "Send the record"], 1),
      [
        { label: "Request type", value: index > 5 ? "Bulk mail" : "Single patient" },
        { label: "Missing", value: index % 2 ? "Office note" : "Operative note" },
        { label: "Record", value: "Not attached" },
        { label: "Date asked", value: "Sep 16, 2026" },
      ],
      ["Attach record"],
      index < 2 ? "Urgent" : "Routine",
      index < 2 ? "Sep 28, 2026" : "Oct 30, 2026",
    ),
  ),
  ...Array.from({ length: 4 }, () =>
    more(
      "records",
      "Medical records",
      "Record attached",
      "open",
      "Yellow",
      "The file is on the claim and can be sent.",
      "Send the record, then the claim can move.",
      stepsThrough(["Waiting for medical records", "Record attached", "Send the record"], 1),
      [
        { label: "Request type", value: "Single patient" },
        { label: "Record", value: "operative-note.pdf" },
        { label: "How to send", value: "Portal, then fax" },
      ],
      ["Send by portal"],
      "Routine",
      "Nov 2, 2026",
    ),
  ),
  ...Array.from({ length: 2 }, () =>
    more(
      "records",
      "Medical records",
      "Waiting for medical records",
      "waiting",
      "Yellow",
      "A page is still missing from a multi-patient packet.",
      "Attach the missing page.",
      stepsThrough(["Bulk request", "Waiting for medical records", "Send the record"], 1),
      [
        { label: "Request type", value: "Bulk mail" },
        { label: "Missing", value: "Operative note" },
        { label: "Record", value: "Not attached" },
      ],
      ["Attach record"],
    ),
  ),
  ...Array.from({ length: 7 }, (_, index) =>
    more(
      "appeals",
      "Appeals",
      "Reconsideration upheld",
      index === 0 ? "deadline" : "open",
      "Red",
      "A reconsideration was sent and upheld. Tries remain.",
      "Dispute it before the response date.",
      stepsThrough(["Copied to appeals", "Appeals", "Outcome"], 1),
      [
        { label: "Denial reason", value: "Medical necessity" },
        { label: "Tries used", value: "1 of 2" },
        { label: "Last send", value: index % 2 ? "Mail" : "Portal" },
      ],
      ["Dispute"],
      index === 0 ? "Urgent" : "Routine",
      index === 0 ? "Oct 1, 2026" : "Oct 26, 2026",
    ),
  ),
  ...Array.from({ length: 5 }, () =>
    more(
      "appeals",
      "Appeals",
      "Coding error",
      "open",
      "Red",
      "The denial is a code or modifier, not a policy dispute.",
      "Correct it and resubmit.",
      stepsThrough(["Red on the tracker", "Coding error", "Resubmit"], 1),
      [
        { label: "Denial reason", value: "Coding" },
        { label: "CPT", value: "99213" },
        { label: "Tries used", value: "0 of 2" },
      ],
      ["Correct and resubmit"],
    ),
  ),
  ...Array.from({ length: 2 }, () =>
    more(
      "appeals",
      "Appeals",
      "Valid denial",
      "waiting",
      "Red",
      "Both tries are used. Adjust it off.",
      "Adjust off, and record why.",
      stepsThrough(["Appeal sent", "Upheld", "Adjust off"], 2),
      [
        { label: "Denial reason", value: "Valid. Tries exhausted." },
        { label: "Tries used", value: "2 of 2" },
        { label: "Last send", value: "Fax" },
      ],
      ["Adjust off"],
      "Routine",
      "Sep 20, 2026",
    ),
  ),
  ...Array.from({ length: 7 }, () =>
    more(
      "billing",
      "Billing",
      "Ready to post",
      "open",
      "White",
      "Insurance paid. Read the remark before posting.",
      "Post the payment in AdvancedMD.",
      stepsThrough(["EDI received", "ERA review", "Post payment"], 1),
      [
        { label: "Insurance paid", value: "$420.00" },
        { label: "Patient paid", value: "$0.00" },
        { label: "Patient responsibility", value: "$30.00" },
        { label: "Write-off", value: "$15.00" },
        { label: "Remark", value: "PR1 deductible" },
        { label: "Date of service", value: "Aug 12, 2026" },
        { label: "CPT", value: "99214" },
      ],
      ["Post payment"],
      "Routine",
      "Nov 3, 2026",
    ),
  ),
  ...Array.from({ length: 4 }, () =>
    more(
      "billing",
      "Billing",
      "Hold",
      "waiting",
      "White",
      "The ERA line looks green, but there is no payment and no write-off.",
      "Hold it so the patient is not billed.",
      stepsThrough(["ERA line", "Hold", "Work from the EDI"], 1),
      [
        { label: "Insurance paid", value: "$0.00" },
        { label: "Patient paid", value: "$0.00" },
        { label: "Patient responsibility", value: "$860.00" },
        { label: "Write-off", value: "None" },
        { label: "Remark", value: "Code did not pay" },
        { label: "Date of service", value: "Jul 22, 2026" },
        { label: "CPT", value: "31231" },
      ],
      ["Hold — do not bill patient"],
      "Urgent",
      "Oct 5, 2026",
    ),
  ),
  ...Array.from({ length: 2 }, () =>
    more(
      "billing",
      "Billing",
      "Copay over-apply",
      "open",
      "White",
      "A copay is already on the account.",
      "Unapply the copay, then post.",
      stepsThrough(["ERA line", "Copay conflict", "Post payment"], 1),
      [
        { label: "Insurance paid", value: "$90.00" },
        { label: "Patient paid", value: "$20.00 copay" },
        { label: "Write-off", value: "$0.00" },
        { label: "Over-apply", value: "$20.00" },
        { label: "CPT", value: "95004" },
      ],
      ["Unapply copay", "Hold — do not bill patient"],
    ),
  ),
];

initialClaims.push(...moreClaims);
